### PR TITLE
Update AbstractMetaClient.java

### PR DESCRIPTION
**Pull request by ianhhhhhhhhe**
Check if the address is a valid uri address

### CODE REVIEW

**Review by laura-ding — DISMISSED** [review]

**Review by laura-ding — COMMENTED** [review]
@ianhhhhhhhhe Please solve the code type. code type checks no pass.

**Comment by ianhhhhhhhhe** [comment]
> @ianhhhhhhhhe Please solve the code type. code type checks no pass.

**Comment by ianhhhhhhhhe** [comment]
> @ianhhhhhhhhe Please solve the code type. code type checks no pass.

ok, fixed it

**Comment by Nicole00** [comment]
Thanks for your contribution~~ Now you can ignore the failed build process, we'll merge it when #288  is merged.

**Review by laura-ding — APPROVED** [review]

**Pull request merged**
