### PR TITLE
add executeJsonWithParameter, executeJson to SessionPool

### PR DESCRIPTION
**Pull request by cjdxhjj**
## What type of PR is this?
- [ ] bug
- [x] feature
- [x] enhancement

#### Description:
add executeJsonWithParameter, executeJson to SessionPool

### CODE REVIEW

**Comment by Nicole00** [comment]
there's two checkstyle violations, could you please format the code?

**Review by Nicole00 — APPROVED** [review]
LGTM！Thanks @cjdxhjj very much!

**Comment by cjdxhjj** [comment]
@Nicole00 thanks

**Comment by QingZ11** [comment]
> @Nicole00 thanks

Thank you for your great contribution, cjdxhjj.

**Pull request merged**
