### PR TITLE
fix: support get all host address(#489)

### PR DESCRIPTION
**Pull request by chenzuyibao**
close https://github.com/vesoft-inc/nebula-java/issues/489 
支持域名解析所有IP地址

### CODE REVIEW

**Comment by Nicole00** [comment]
Hi, thanks for your contribution, could you please sign the CLA first?

**Comment by chenzuyibao** [comment]
已经登录了呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月16日(星期三) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vesoft-inc/nebula-java] fix: support get all host address(#489) (PR #491)





 
Hi, thanks for your contribution, could you please sign the CLA first?

**Comment by chenzuyibao** [comment]
似乎是单测环境不支持语句了？能否帮忙检查下 @Nicole00

**Comment by Nicole00** [comment]
> 已经登录了呀
maybe you should re-push your pr after sign cla.

**Comment by chenzuyibao** [comment]
我是否应该提PR到master分支，而不是我们项目使用的版本2.5.1，第一次PR的过程总是问题很多 😁 @Nicole00

**Comment by Nicole00** [comment]
> 我是否应该提PR到master分支，而不是我们项目使用的版本2.5.1，第一次PR的过程总是问题很多 😁 @Nicole00

Sorry, I missed the base branch information. Yeah, you should push your `nebula-java-489` branch to master.

**Comment by Nicole00** [comment]
you should config your email for your github account.  
try `git config --global user.email "xxx"`
And then, git push again.

**Comment by wey-gu** [comment]
It seems that we need two conditions to fulfill:

1. sign this with your github user https://cla-assistant.io/vesoft-inc/nebula-java?pullRequest=491
2. ensure commit's auther and email matched the github credential

looks like the email address doesn't match the GitHub user?

@chenzuyibao you could try change comment authors and push force, or if you are not familiar with them, you could create another local branch locally, apply file changes to new branch and commit with the expected author name and email.

```
commit 415cb0c36ba8cefdf4f3198d10ebb2007d1b6a24 (HEAD -> nebula-java-489, origin/nebula-java-489)
Author: chenzuyibao <chenzuyibao@163.com>
Date:   Wed Nov 16 15:57:08 2022 +0800

    fix: for issue #489

commit ba7064dc0c1bda739e8caf9ece5c7d054903236d
Author: chenzuyibao <960443387@qq.com>
Date:   Wed Nov 16 15:10:12 2022 +0800

    Update README.md

commit 724fcd268a350c882df2395ea48f786cfda4603d
Merge: e1861c8 f4431aa
Author: chenzuyibao <960443387@qq.com>
Date:   Wed Nov 16 15:07:05 2022 +0800

    Merge branch 'master' into nebula-java-489

commit e1861c837254c7685e7cb8dd82f3a1c1b2e37c52
Author: chenzuyibao <chenzuyibao@163.com>
Date:   Wed Nov 16 10:14:22 2022 +0800

    fix: for issue #489
```

**Comment by chenzuyibao** [comment]
呼~，同一个账号，不同邮箱提交导致的，感谢指导！！ @Nicole00 @wey-gu

**Review by Nicole00 — APPROVED** [review]
LGTM

**Pull request merged**
