### PR TITLE
add executeJsonWithParameter, executeJson to SessionPool

### PR DESCRIPTION
**Pull request by cjdxhjj**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

### CODE REVIEW

**Comment by QingZ11** [comment]
> ## What type of PR is this?
> * [ ]  bug
> * [ ]  feature
> * [x]  enhancement
> 
> ## What problem(s) does this PR solve?
> #### Issue(s) number:
> #### Description:
> ## How do you solve it?
> ## Special notes for your reviewer, ex. impact of this fix, design document, etc:

谢谢 [cjdxhjj](https://github.com/cjdxhjj) 的 PR，你可以点击下 CLA 图标签署下 CLA 协议么（协议的大概意思是你是这块变更内容的所有者，但是 nebula 有使用权）

Thank you,[cjdxhjj](https://github.com/cjdxhjj), for the pull request. Could you please click on the CLA icon and sign the CLA agreement? The agreement basically states that you are the owner of the changes made in this contribution, but Nebula has the right to use them.

**Comment by cjdxhjj** [comment]
i have signed the cla, but the status looks not signed.
image

**Comment by Shinji-IkariG** [comment]
看起来你在git命令行中使用了‘petzold’作为用户名而非‘[cjdxhjj](https://github.com/cjdxhjj)’ 请更新本地git配置并重新commit

It looks like you used 'petzold' as the username in the git command line instead of '[cjdxhjj](https://github.com/cjdxhjj)' Please update the local git configuration and commit again

**Comment by cjdxhjj** [comment]
oh ,i will repush later

**Pull request closed without merging**
