### PR TITLE
change labels to tagNames

### PR DESCRIPTION
**Pull request by sekingme**
Change the name of get tagNames method. 

The origin method of 'labels' is confuse!

### CODE REVIEW

**Review by laura-ding — APPROVED** [review]
Thank you for your attention to this. The ci is failed, I will merge it after https://github.com/vesoft-inc/nebula-java/pull/270 is merged.

**Comment by laura-ding** [comment]
@sekingme Please signed the CLA.

**Comment by sekingme** [comment]
> @sekingme Please signed the CLA.

done, please check? @laura-ding

**Comment by laura-ding** [comment]
> > @sekingme Please signed the CLA.
> 
> done, please check? @laura-ding

屏幕快照 2021-03-18 14 36 15

It's no done!

**Comment by sekingme** [comment]
> > > @sekingme Please signed the CLA.
> > 
> > 
> > done, please check? @laura-ding
> 
> 屏幕快照 2021-03-18 14 36 15
> 
> It's no done!

I click the agreement several times, but it does not seem works.

**Comment by sekingme** [comment]
> > > @sekingme Please signed the CLA.
> > 
> > 
> > done, please check? @laura-ding
> 
> 屏幕快照 2021-03-18 14 36 15
> 
> It's no done!

the pr is push with a wrong user. Please close this pr and I will push with sekingme again.

**Comment by sekingme** [comment]
> > > @sekingme Please signed the CLA.
> > 
> > 
> > done, please check? @laura-ding
> 
> 屏幕快照 2021-03-18 14 36 15
> 
> It's no done!

@laura-ding 
Use a wrong user before.
Please close these prs: #269 #273 #274
And merge this: #275

**Comment by laura-ding** [comment]
https://github.com/vesoft-inc/nebula-java/pull/275 has done it, so close it.

**Pull request closed without merging**
