### PR TITLE
graph ORM

### PR DESCRIPTION
**Pull request by Anyzm**
add graph ORM
[https://github.com/vesoft-inc/nebula-java/issues/347](issues/347)

### CODE REVIEW

**Comment by wey-gu** [comment]
@jamieliu1023, please help involve the dev community in discussion for the great ORM PR :)

**Comment by jamieliu1023** [comment]
@Anyzm Thank you sooooo much for the code! @Nicole00 @klay-ke Please take a look at this.

**Comment by klay-ke** [comment]
Hi @Anyzm. Really appreciated the pull request and your invaluable contribution, we are gonna take a look and have reviews within team. Will get back to you soon, thanks.

**Comment by Anyzm** [comment]
在个人仓库已发布，过段时间上传中央仓库，开发者也可以下载源码自己改。
通过捐赠仓库的形式贡献ORM
https://github.com/Anyzm/graph-ocean

**Pull request closed without merging**
